server:
  port: 8090



spring:
  resources:
    static-locations: classpath:templates/
  mvc:
    view:
      prefix: /
      suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/task_management?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8 #编码
    suffix: .html #模板后缀
    mode: HTML #模板
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
  mail:
    host: smtp.qq.com
    username: 1742730084@qq.com
    password: yicqeqrldihpbhig
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
    ##         ssl:
    ##           enable :true
    default-encoding: utf-8
mybatis:
  type-aliases-package: com.task.bean
  mapper-locations: classpath:mapper/*Mapper.xml
  ## 实体类驼峰
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      bibn:
        mybatisplass:
          dao=debug: